### ISSUE TITLE
Rendering Bug With The About Page

### ISSUE THREAD

**Issue by kmarshall98** [info442-sp21/c-team#32]
**Severity** Minor
**Description** After signing into a google account, the about page does not populate in the page. To get the about page to render the user must click to a different page then back to the about page. This is necessary/useful because the first screen we want the user to see is the about page to allow them to understand the project and know how to use the website. 

**Steps**
1) Sign into google account
2) Current: Populates an about page with no text
     Expected Outcome: Should populate a page with our names, description, and problem context.

<img width="1102" alt="Screen Shot 2021-05-25 at 1 46 13 PM" src="https://user-images.githubusercontent.com/46639384/119566088-94261a80-bd5f-11eb-828e-b37a84c232e7.png">

_Found on a Safari macOS Big Sur 11.2.3_

**Comment by kmarshall98** [comment]
TO DO

**Comment by cherimarie** [comment]
I agree with the reporter that this is a major issue. It prevents the user from viewing one third of the site's total content.

**Comment by drishtividyarthi** [comment]
fixed with issue "Fixed feed"

**Comment by drishtividyarthi** [comment]
fixed with "fixed feed"
