### ISSUE TITLE
Creating an error message when new posts are empty

### ISSUE THREAD

**Issue by dorilusions** [info442-sp21/c-team#34]
Currently, users do not seem to be able to add a new post when either the title or the message boxes are empty.  However, there is no indicator that the user shouldn't be able to when they try to do so.

As such, it may be helpful for some sort of error message (e.g. "Please add a title to your post") to pop up when a user tries to submit a post without a title/message.

**Comment by kmarshall98** [comment]
Nice To Have/TO DO

**Comment by drishtividyarthi** [comment]
Fixed from Mequanent on 6/2
