### ISSUE TITLE
New Feature Request: See other people's posts. 

### ISSUE THREAD

**Issue by kristina-te** [info442-sp21/c-team#36]
Users have an ability to see other people's posts to cultivate this community environment and further promote local businesses. This will help create organic outreach and help small businesses instead of keeping reviews local.

**Comment by yejukim** [comment]
This is a TO-DO as our system requirements include a business posting feed that allows people to find local businesses.

**Comment by yejukim** [comment]
The users should not be able to see other's posts in this commit: https://github.com/info442-sp21/c-team/commit/3f69d1e34e9006bde4a8ad809ced9c64aae8d230
