### ISSUE TITLE
Allows completely empty posts to be made

### ISSUE THREAD

**Issue by ashshah1** [info442-sp21/c-team#37]
Creating a post comprised entirely of spaces is considered a valid post and shows up under "My Posts"

<img width="376" alt="Screen Shot 2021-05-25 at 2 20 19 PM" src="https://user-images.githubusercontent.com/55997736/119569972-57105700-bd64-11eb-8c87-a5ec49f5eb5d.png">

Expected Behavior
Some form of form validation that shows an error

mac OS, Chrome

**Comment by kmarshall98** [comment]
TO DO

**Comment by cherimarie** [comment]
For grading purposes, I won't consider this a duplicate, but it's fine to do so for issue organization.
