### ISSUE TITLE
Requested feature: Communicate with other users

### ISSUE THREAD

**Issue by ndemmel** [info442-sp21/c-team#38]
If I am right in understanding that your website is for small businesses to connect with the communities they serve, then I would like a feature that lets me communicate with other users on the website. This feature could look like writing a post and giving it to someone else to read, like @'ing someone on Twitter or Discord, or whatever your team decides work best with your mission and current implementation. This feature directly helps users on your website connect with small businesses.

**Comment by yejukim** [comment]
Duplicate: See #36

**Comment by cherimarie** [comment]
This is not a duplicate. #36 is for post visibility. This one is for messaging or mentioning a user in a post.
