### ISSUE TITLE
New Feature Requests: Additional information on what to write in posts. 

### ISSUE THREAD

**Issue by kristina-te** [info442-sp21/c-team#41]
Users must be able to understand what they should be writing the the text field sections when they are trying to post as it is a little ambiguous. This will help create better content creation from users by giving them examples to create consistency and guide them in the right direction.

**Comment by drishtividyarthi** [comment]
Will add to the about page, with clearer instructions

**Comment by yejukim** [comment]
We updated our about page to have clearer instructions on what to post about in this commit: https://github.com/info442-sp21/c-team/commit/979c9ece42b4a0617e9a5a08845ca3f54382dec7
