### ISSUE TITLE
[Major] Nothing shows on about page on mobile

### ISSUE THREAD

**Issue by tichx** [info442-sp21/c-team#42]
**Describe the bug**
After log in, there is no content on the about page

**Severity**
Major

**To Reproduce**
1. Login
2. Wait for redirect
3. land on the about page

**Expected behavior**
Show the about page content whatever it is.

**Current behavior**
Show a blank page on the about page.

**Screenshots**
<img width="425" alt="WX20210525-142444@2x" src="https://user-images.githubusercontent.com/12144060/119570875-807db280-bd65-11eb-912b-a5c655b59b29.png">

**Mobile :**
* Device: iPhone X
* OS: iOS
* Browser: Safari
* Version: V14.0.1

**Comment by kmarshall98** [comment]
Duplicate: Already a rendering issue in general
