### ISSUE TITLE
[Minor] The sign out button was cover the site title on mobile

### ISSUE THREAD

**Issue by tichx** [info442-sp21/c-team#46]
**Describe the bug**
After logging in, the user can see the sign out button covers the title of the site

**Severity**
Minor

**To Reproduce**
1. Login
2. Wait for redirect
3. land on the about page

**Expected behavior**
Having the sign out button not overlapping with the title

**Current behavior**
I can only see "Community" and the "coders " part was left out

**Screenshots**
<img width="425" alt="WX20210525-142444@2x" src="https://user-images.githubusercontent.com/12144060/119570875-807db280-bd65-11eb-912b-a5c655b59b29.png">

**Mobile :**
* Device: iPhone X
* OS: iOS
* Browser: Safari
* Version: V14.0.1

**Comment by yejukim** [comment]
Duplicate: see #35
