### ISSUE TITLE
Instructions on what to post

### ISSUE THREAD

**Issue by atnguyenduy** [info442-sp21/c-team#49]
**Describe the bug**
Users don't know what to post 

**To Reproduce**
1. Go to https://communitycode-52932.web.app/
2. Go to 'Add posts' 
3. Write instructions 

**Expected behaviors*
Expected to see a brief intro or instructions on what to post

**Screenshots** 
![image](https://user-images.githubusercontent.com/41980535/119571288-0699f900-bd66-11eb-9495-22dd0974533e.png)

**Desktop (please complete the following information):**
Device: Lenovo Thinkpad laptop
Windows 10 Enterprise / Version 20H2 / OS build 19042.804
Browser: Edge

**Comment by yejukim** [comment]
Will add to the about page, with clearer instructions (see #41)
