### ISSUE TITLE
When opening on mobile device the signout button is blocking the title header

### ISSUE THREAD

**Issue by bphan23** [info442-sp21/c-team#51]
* Severity - Major
* When uploaded the website on a mobile device, after signing into an email the signout button is blocking the title header.
* Used - Safari on the iPhone 11
* CSS styling to make the signout button not block the header. Adjust the margins or use paddings.
* The sign-out button is blocking the title header.
* Expected to be able to see everything I see when opening in on a desktop or laptop.

**Comment by kmarshall98** [comment]
Duplicate (see #42 )
