### ISSUE TITLE
Sign Up Button

### ISSUE THREAD

**Issue by gidchia** [info442-sp21/c-team#60]
**Describe the enhancement**
The requirement states "Users should see sign-in and sign-up buttons on the navigation bar to be able to log-in or create an account using their business name, address and email."

There is no "sign up" option, only a google sign in option.

**To Reproduce**

1. Go to address: https://communitycode-52932.web.app/

**Desktop (please complete the following information):**

OS: iOS
Browser - Chrome
Version - Version 90.0.4430.85

**Comment by drishtividyarthi** [comment]
Out of Scope

**Comment by cherimarie** [comment]
I'd call this a minor bug. Advertising a feature to the user that isn't available is a poor user experience. If signing up without a google account isn't a feature, removing it from the prompt would reduce confusion for users.
