### ISSUE TITLE
Bottom Banner

### ISSUE THREAD

**Issue by gidchia** [info442-sp21/c-team#61]
**Describe the enhancement**
Would be nice to have the bottom banner be anchored to the bottom of the page, instead of having it depend on the contents of the page.

**To Reproduce**

1. Sign in with Google
2. Observe that if there is no content on the main page, the bottom banner merges with the nav bar.

**Desktop (please complete the following information):**
OS: iOS
Browser - Chrome
Version - Version 90.0.4430.85

**Comment by drishtividyarthi** [comment]
Duplicate: See #56
